channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - pip
  - cython
  - matplotlib
  - pyamg
  - mayavi
  - pandas
  - openpyxl
  - scikit-image
  - scikit-learn
  - boto3
  - awscli
  - openjdk=8
  - pip:
    - --extra-index-url https://pypi.fury.io/dd8/
    - matplotlib-scalebar
    - PyQt5
    - simpleitk==1.2.0rc2.dev1162+g2a79d
    - python-bioformats==1.1.0
