channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - pip
  - cython
  - matplotlib
  - pyamg
  - mayavi
  - pandas
  - scikit-image
  - pip:
    - matplotlib-scalebar
    - PyQt5
    - simpleitk
    - "git+https://github.com/LeeKamentsky/python-javabridge.git"
    - python-bioformats==1.1.0
