name: clr2
channels:
- defaults
- clinicalgraphics  # for VTK 7
dependencies:
- python=3.6
- numpy
- scipy
- matplotlib
- pyqt=5
- vtk=7
- cython
- pygments
- pip:
  - matplotlib-scalebar
  - "git+https://github.com/enthought/traits.git@a99b3f64d50c5f7f28ffc01bf69419b061f9e976"
  - "git+https://github.com/enthought/pyface.git@3c0d22408ef9829e9e03bfa73177c07067003d15"
  - "git+https://github.com/enthought/traitsui.git@768939ca2bc93fe13475445ebd54dcbdd6a23387"
  - "git+https://github.com/enthought/mayavi.git@1ab6e5e3d991ae6dd5438dbcc1d34fa40e224d1b"
  - "git+https://github.com/LeeKamentsky/python-javabridge.git@2b6e7b067aeeac27fc5359ebba56f316a85527cc"
  - python-bioformats==1.1.0
  - "git+https://github.com/the4thchild/scikit-image.git@b88bf88dc1caa133e914e589fd094185dc61e9b1"
